import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import About from './About'
import Homepage from './landing'
import Secondpage from './secondpage'
import Thirdpage from './third'
import Contact from './contact'
import Reviews from './Reviews'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='overflow-hidden'>
        <Navbar/>
        <Homepage/>
        <Secondpage/>
        
        <About/>
        <Contact/>
        <Thirdpage/>
      </main>
    </div>
  )
}
